### ISSUE TITLE
CIが通らない

### ISSUE THREAD

**Issue by s-hosoai** [toppers/hakoniwa-conductor#11]
#9からのものは，ライブラリと実装のズレによるものなので，認識済み
#15以降のものは現状と同じものが出ている．
出ているエラーと，発生時期がPythonのClientライブラリ追加時期付近なので，Python絡みの何かっぽいがよく分からない．これだからｐｙてょんは，，

**Comment by tmori** [comment]
Mac(Intel)で問題が起きているらしい。

<img width="480" alt="スクリーンショット 2023-12-30 18 37 08" src="https://github.com/toppers/hakoniwa-conductor/assets/164193/8b4bb7b5-404b-43c2-a013-eefdee998a3c">

**Comment by tmori** [comment]
直しました。
